<?php

/**
 * BaseExistingMobile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $mail_mobile
 * @property enum $prefecture
 * @property boolean $mail_block_flag
 * @property Doctrine_Collection $ExistingWithdrawal
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getMailMobile()         Returns the current record's "mail_mobile" value
 * @method enum                getPrefecture()         Returns the current record's "prefecture" value
 * @method boolean             getMailBlockFlag()      Returns the current record's "mail_block_flag" value
 * @method Doctrine_Collection getExistingWithdrawal() Returns the current record's "ExistingWithdrawal" collection
 * @method ExistingMobile      setId()                 Sets the current record's "id" value
 * @method ExistingMobile      setMailMobile()         Sets the current record's "mail_mobile" value
 * @method ExistingMobile      setPrefecture()         Sets the current record's "prefecture" value
 * @method ExistingMobile      setMailBlockFlag()      Sets the current record's "mail_block_flag" value
 * @method ExistingMobile      setExistingWithdrawal() Sets the current record's "ExistingWithdrawal" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseExistingMobile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('existing_mobile');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('mail_mobile', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('prefecture', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '北海道',
              1 => '青森県',
              2 => '岩手県',
              3 => '宮城県',
              4 => '秋田県',
              5 => '山形県',
              6 => '福島県',
              7 => '茨城県',
              8 => '栃木県',
              9 => '群馬県',
              10 => '埼玉県',
              11 => '千葉県',
              12 => '東京都',
              13 => '神奈川県',
              14 => '新潟県',
              15 => '富山県',
              16 => '石川県',
              17 => '>福井県',
              18 => '山梨県',
              19 => '長野県',
              20 => '岐阜県',
              21 => '静岡県',
              22 => '愛知県',
              23 => '三重県',
              24 => '滋賀県',
              25 => '京都府',
              26 => '大阪府',
              27 => '兵庫県',
              28 => '奈良県',
              29 => '和歌山県',
              30 => '鳥取県',
              31 => '島根県',
              32 => '岡山県',
              33 => '広島県',
              34 => '山口県',
              35 => '徳島県',
              36 => '香川県',
              37 => '愛媛県',
              38 => '高知県',
              39 => '福岡県',
              40 => '佐賀県',
              41 => '長崎県',
              42 => '熊本県',
              43 => '大分県',
              44 => '宮崎県',
              45 => '鹿児島県',
              46 => '沖縄県',
              47 => '日本国外',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('mail_block_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ExistingWithdrawal', array(
             'local' => 'id',
             'foreign' => 'existing_mobile_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}