<?php

/**
 * BaseShop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $name
 * @property string $zip_code
 * @property string $prefecture
 * @property string $address
 * @property string $tel
 * @property string $fax
 * @property string $url1
 * @property string $url2
 * @property boolean $aq_flag
 * @property boolean $maquiexpert_flag
 * @property boolean $salon_flag
 * @property Doctrine_Collection $FavoriteMembers
 * 
 * @method string              getId()               Returns the current record's "id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method string              getZipCode()          Returns the current record's "zip_code" value
 * @method string              getPrefecture()       Returns the current record's "prefecture" value
 * @method string              getAddress()          Returns the current record's "address" value
 * @method string              getTel()              Returns the current record's "tel" value
 * @method string              getFax()              Returns the current record's "fax" value
 * @method string              getUrl1()             Returns the current record's "url1" value
 * @method string              getUrl2()             Returns the current record's "url2" value
 * @method boolean             getAqFlag()           Returns the current record's "aq_flag" value
 * @method boolean             getMaquiexpertFlag()  Returns the current record's "maquiexpert_flag" value
 * @method boolean             getSalonFlag()        Returns the current record's "salon_flag" value
 * @method Doctrine_Collection getFavoriteMembers()  Returns the current record's "FavoriteMembers" collection
 * @method Shop                setId()               Sets the current record's "id" value
 * @method Shop                setName()             Sets the current record's "name" value
 * @method Shop                setZipCode()          Sets the current record's "zip_code" value
 * @method Shop                setPrefecture()       Sets the current record's "prefecture" value
 * @method Shop                setAddress()          Sets the current record's "address" value
 * @method Shop                setTel()              Sets the current record's "tel" value
 * @method Shop                setFax()              Sets the current record's "fax" value
 * @method Shop                setUrl1()             Sets the current record's "url1" value
 * @method Shop                setUrl2()             Sets the current record's "url2" value
 * @method Shop                setAqFlag()           Sets the current record's "aq_flag" value
 * @method Shop                setMaquiexpertFlag()  Sets the current record's "maquiexpert_flag" value
 * @method Shop                setSalonFlag()        Sets the current record's "salon_flag" value
 * @method Shop                setFavoriteMembers()  Sets the current record's "FavoriteMembers" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseShop extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop');
        $this->hasColumn('id', 'string', 7, array(
             'type' => 'string',
             'primary' => true,
             'length' => 7,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('zip_code', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 8,
             ));
        $this->hasColumn('prefecture', 'string', 4, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('tel', 'string', 13, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 13,
             ));
        $this->hasColumn('fax', 'string', 13, array(
             'type' => 'string',
             'length' => 13,
             ));
        $this->hasColumn('url1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('url2', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('aq_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('maquiexpert_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('salon_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));


        $this->index('name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->index('prefecture', array(
             'fields' => 
             array(
              0 => 'prefecture',
             ),
             ));
        $this->index('address', array(
             'fields' => 
             array(
              0 => 'address',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Member as FavoriteMembers', array(
             'refClass' => 'ShopFavorite',
             'local' => 'shop_id',
             'foreign' => 'member_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}