<?php

/**
 * BaseProductSearchLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $age
 * @property enum $prefecture
 * @property boolean $login_flag
 * @property string $line
 * @property string $category
 * @property string $sub_category
 * @property string $effect
 * @property string $sort
 * @property integer $hit
 * @property boolean $valid_flag
 * @property Member $Member
 * @property Doctrine_Collection $AccessLogs
 * @property Doctrine_Collection $Keywords
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method integer             getMemberId()     Returns the current record's "member_id" value
 * @method integer             getAge()          Returns the current record's "age" value
 * @method enum                getPrefecture()   Returns the current record's "prefecture" value
 * @method boolean             getLoginFlag()    Returns the current record's "login_flag" value
 * @method string              getLine()         Returns the current record's "line" value
 * @method string              getCategory()     Returns the current record's "category" value
 * @method string              getSubCategory()  Returns the current record's "sub_category" value
 * @method string              getEffect()       Returns the current record's "effect" value
 * @method string              getSort()         Returns the current record's "sort" value
 * @method integer             getHit()          Returns the current record's "hit" value
 * @method boolean             getValidFlag()    Returns the current record's "valid_flag" value
 * @method Member              getMember()       Returns the current record's "Member" value
 * @method Doctrine_Collection getAccessLogs()   Returns the current record's "AccessLogs" collection
 * @method Doctrine_Collection getKeywords()     Returns the current record's "Keywords" collection
 * @method ProductSearchLog    setId()           Sets the current record's "id" value
 * @method ProductSearchLog    setMemberId()     Sets the current record's "member_id" value
 * @method ProductSearchLog    setAge()          Sets the current record's "age" value
 * @method ProductSearchLog    setPrefecture()   Sets the current record's "prefecture" value
 * @method ProductSearchLog    setLoginFlag()    Sets the current record's "login_flag" value
 * @method ProductSearchLog    setLine()         Sets the current record's "line" value
 * @method ProductSearchLog    setCategory()     Sets the current record's "category" value
 * @method ProductSearchLog    setSubCategory()  Sets the current record's "sub_category" value
 * @method ProductSearchLog    setEffect()       Sets the current record's "effect" value
 * @method ProductSearchLog    setSort()         Sets the current record's "sort" value
 * @method ProductSearchLog    setHit()          Sets the current record's "hit" value
 * @method ProductSearchLog    setValidFlag()    Sets the current record's "valid_flag" value
 * @method ProductSearchLog    setMember()       Sets the current record's "Member" value
 * @method ProductSearchLog    setAccessLogs()   Sets the current record's "AccessLogs" collection
 * @method ProductSearchLog    setKeywords()     Sets the current record's "Keywords" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseProductSearchLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_search_log');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('age', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('prefecture', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '北海道',
              1 => '青森県',
              2 => '岩手県',
              3 => '宮城県',
              4 => '秋田県',
              5 => '山形県',
              6 => '福島県',
              7 => '茨城県',
              8 => '栃木県',
              9 => '群馬県',
              10 => '埼玉県',
              11 => '千葉県',
              12 => '東京都',
              13 => '神奈川県',
              14 => '新潟県',
              15 => '富山県',
              16 => '石川県',
              17 => '福井県',
              18 => '山梨県',
              19 => '長野県',
              20 => '岐阜県',
              21 => '静岡県',
              22 => '愛知県',
              23 => '三重県',
              24 => '滋賀県',
              25 => '京都府',
              26 => '大阪府',
              27 => '兵庫県',
              28 => '奈良県',
              29 => '和歌山県',
              30 => '鳥取県',
              31 => '島根県',
              32 => '岡山県',
              33 => '広島県',
              34 => '山口県',
              35 => '徳島県',
              36 => '香川県',
              37 => '愛媛県',
              38 => '高知県',
              39 => '福岡県',
              40 => '佐賀県',
              41 => '長崎県',
              42 => '熊本県',
              43 => '大分県',
              44 => '宮崎県',
              45 => '鹿児島県',
              46 => '沖縄県',
             ),
             ));
        $this->hasColumn('login_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('line', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('category', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sub_category', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('effect', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sort', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('hit', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('valid_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasMany('ProductAccessLog as AccessLogs', array(
             'local' => 'id',
             'foreign' => 'search_log_id'));

        $this->hasMany('ProductSearchKeywordLog as Keywords', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}