<?php

/**
 * BaseFaqDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $question
 * @property string $answer
 * @property integer $priority
 * @property boolean $popular_flag
 * @property text $search_index
 * @property Doctrine_Collection $RelatedDetails
 * @property Doctrine_Collection $SubCategories
 * @property Doctrine_Collection $Contents
 * @property Doctrine_Collection $FaqDetail
 * @property Doctrine_Collection $FaqDetailRelated
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getQuestion()         Returns the current record's "question" value
 * @method string              getAnswer()           Returns the current record's "answer" value
 * @method integer             getPriority()         Returns the current record's "priority" value
 * @method boolean             getPopularFlag()      Returns the current record's "popular_flag" value
 * @method text                getSearchIndex()      Returns the current record's "search_index" value
 * @method Doctrine_Collection getRelatedDetails()   Returns the current record's "RelatedDetails" collection
 * @method Doctrine_Collection getSubCategories()    Returns the current record's "SubCategories" collection
 * @method Doctrine_Collection getContents()         Returns the current record's "Contents" collection
 * @method Doctrine_Collection getFaqDetail()        Returns the current record's "FaqDetail" collection
 * @method Doctrine_Collection getFaqDetailRelated() Returns the current record's "FaqDetailRelated" collection
 * @method FaqDetail           setId()               Sets the current record's "id" value
 * @method FaqDetail           setQuestion()         Sets the current record's "question" value
 * @method FaqDetail           setAnswer()           Sets the current record's "answer" value
 * @method FaqDetail           setPriority()         Sets the current record's "priority" value
 * @method FaqDetail           setPopularFlag()      Sets the current record's "popular_flag" value
 * @method FaqDetail           setSearchIndex()      Sets the current record's "search_index" value
 * @method FaqDetail           setRelatedDetails()   Sets the current record's "RelatedDetails" collection
 * @method FaqDetail           setSubCategories()    Sets the current record's "SubCategories" collection
 * @method FaqDetail           setContents()         Sets the current record's "Contents" collection
 * @method FaqDetail           setFaqDetail()        Sets the current record's "FaqDetail" collection
 * @method FaqDetail           setFaqDetailRelated() Sets the current record's "FaqDetailRelated" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseFaqDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_detail');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('question', 'string', 1024, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1024,
             ));
        $this->hasColumn('answer', 'string', 4096, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4096,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('popular_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('search_index', 'text', null, array(
             'type' => 'text',
             ));


        $this->index('answer', array(
             'fields' => 
             array(
              0 => 'answer',
             ),
             ));
        $this->index('search_index', array(
             'fields' => 
             array(
              'search_index' => 
              array(
              'length' => 255,
              ),
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FaqDetail as RelatedDetails', array(
             'refClass' => 'FaqDetailRelated',
             'local' => 'faq_detail_id1',
             'foreign' => 'faq_detail_id2'));

        $this->hasMany('FaqSubCategory as SubCategories', array(
             'refClass' => 'FaqSubCategoryDetail',
             'local' => 'faq_detail_id',
             'foreign' => 'faq_sub_category_id'));

        $this->hasMany('FaqContent as Contents', array(
             'refClass' => 'FaqContentDetail',
             'local' => 'faq_detail_id',
             'foreign' => 'faq_content_id'));

        $this->hasMany('FaqDetail', array(
             'refClass' => 'FaqDetailRelated',
             'local' => 'faq_detail_id2',
             'foreign' => 'faq_detail_id1'));

        $this->hasMany('FaqDetailRelated', array(
             'local' => 'id',
             'foreign' => 'faq_detail_id2'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}