<?php

/**
 * BaseSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sess_id
 * @property text $sess_data
 * @property integer $sess_time
 * 
 * @method string  getSessId()    Returns the current record's "sess_id" value
 * @method text    getSessData()  Returns the current record's "sess_data" value
 * @method integer getSessTime()  Returns the current record's "sess_time" value
 * @method Session setSessId()    Sets the current record's "sess_id" value
 * @method Session setSessData()  Sets the current record's "sess_data" value
 * @method Session setSessTime()  Sets the current record's "sess_time" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseSession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('sess_id', 'string', 64, array(
             'type' => 'string',
             'primary' => true,
             'length' => 64,
             ));
        $this->hasColumn('sess_data', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('sess_time', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('type', 'MyISAM');
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}