<?php

/**
 * BaseExistingWithdrawal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $existing_mobile_id
 * @property ExistingMobile $ExistingMobile
 * 
 * @method string             getId()                 Returns the current record's "id" value
 * @method integer            getExistingMobileId()   Returns the current record's "existing_mobile_id" value
 * @method ExistingMobile     getExistingMobile()     Returns the current record's "ExistingMobile" value
 * @method ExistingWithdrawal setId()                 Sets the current record's "id" value
 * @method ExistingWithdrawal setExistingMobileId()   Sets the current record's "existing_mobile_id" value
 * @method ExistingWithdrawal setExistingMobile()     Sets the current record's "ExistingMobile" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseExistingWithdrawal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('existing_withdrawal');
        $this->hasColumn('id', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('existing_mobile_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ExistingMobile', array(
             'local' => 'existing_mobile_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}