<?php

/**
 * BaseProductAccessLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property integer $age
 * @property enum $prefecture
 * @property boolean $login_flag
 * @property integer $product_id
 * @property integer $search_log_id
 * @property Member $Member
 * @property Product $Product
 * @property ProductSearchLog $SearchLog
 * 
 * @method integer          getId()            Returns the current record's "id" value
 * @method integer          getMemberId()      Returns the current record's "member_id" value
 * @method integer          getAge()           Returns the current record's "age" value
 * @method enum             getPrefecture()    Returns the current record's "prefecture" value
 * @method boolean          getLoginFlag()     Returns the current record's "login_flag" value
 * @method integer          getProductId()     Returns the current record's "product_id" value
 * @method integer          getSearchLogId()   Returns the current record's "search_log_id" value
 * @method Member           getMember()        Returns the current record's "Member" value
 * @method Product          getProduct()       Returns the current record's "Product" value
 * @method ProductSearchLog getSearchLog()     Returns the current record's "SearchLog" value
 * @method ProductAccessLog setId()            Sets the current record's "id" value
 * @method ProductAccessLog setMemberId()      Sets the current record's "member_id" value
 * @method ProductAccessLog setAge()           Sets the current record's "age" value
 * @method ProductAccessLog setPrefecture()    Sets the current record's "prefecture" value
 * @method ProductAccessLog setLoginFlag()     Sets the current record's "login_flag" value
 * @method ProductAccessLog setProductId()     Sets the current record's "product_id" value
 * @method ProductAccessLog setSearchLogId()   Sets the current record's "search_log_id" value
 * @method ProductAccessLog setMember()        Sets the current record's "Member" value
 * @method ProductAccessLog setProduct()       Sets the current record's "Product" value
 * @method ProductAccessLog setSearchLog()     Sets the current record's "SearchLog" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseProductAccessLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_access_log');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('age', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('prefecture', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '北海道',
              1 => '青森県',
              2 => '岩手県',
              3 => '宮城県',
              4 => '秋田県',
              5 => '山形県',
              6 => '福島県',
              7 => '茨城県',
              8 => '栃木県',
              9 => '群馬県',
              10 => '埼玉県',
              11 => '千葉県',
              12 => '東京都',
              13 => '神奈川県',
              14 => '新潟県',
              15 => '富山県',
              16 => '石川県',
              17 => '福井県',
              18 => '山梨県',
              19 => '長野県',
              20 => '岐阜県',
              21 => '静岡県',
              22 => '愛知県',
              23 => '三重県',
              24 => '滋賀県',
              25 => '京都府',
              26 => '大阪府',
              27 => '兵庫県',
              28 => '奈良県',
              29 => '和歌山県',
              30 => '鳥取県',
              31 => '島根県',
              32 => '岡山県',
              33 => '広島県',
              34 => '山口県',
              35 => '徳島県',
              36 => '香川県',
              37 => '愛媛県',
              38 => '高知県',
              39 => '福岡県',
              40 => '佐賀県',
              41 => '長崎県',
              42 => '熊本県',
              43 => '大分県',
              44 => '宮崎県',
              45 => '鹿児島県',
              46 => '沖縄県',
             ),
             ));
        $this->hasColumn('login_flag', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('search_log_id', 'integer', null, array(
             'type' => 'integer',
             ));


        $this->index('created_at', array(
             'fields' => 
             array(
              0 => 'created_at',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'SET NULL'));

        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ProductSearchLog as SearchLog', array(
             'local' => 'search_log_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}