<?php

/**
 * BaseMailGroupLogicTerm
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $logic_id
 * @property enum $operator
 * @property enum $column_name
 * @property string $value
 * @property MailGroupLogic $Logic
 * 
 * @method integer            getId()          Returns the current record's "id" value
 * @method integer            getLogicId()     Returns the current record's "logic_id" value
 * @method enum               getOperator()    Returns the current record's "operator" value
 * @method enum               getColumnName()  Returns the current record's "column_name" value
 * @method string             getValue()       Returns the current record's "value" value
 * @method MailGroupLogic     getLogic()       Returns the current record's "Logic" value
 * @method MailGroupLogicTerm setId()          Sets the current record's "id" value
 * @method MailGroupLogicTerm setLogicId()     Sets the current record's "logic_id" value
 * @method MailGroupLogicTerm setOperator()    Sets the current record's "operator" value
 * @method MailGroupLogicTerm setColumnName()  Sets the current record's "column_name" value
 * @method MailGroupLogicTerm setValue()       Sets the current record's "value" value
 * @method MailGroupLogicTerm setLogic()       Sets the current record's "Logic" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseMailGroupLogicTerm extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mail_group_logic_term');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('logic_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('operator', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'EQUAL',
              1 => 'NOT EQUAL',
              2 => 'GREATER_THAN',
              3 => 'GREATER_EQUAL',
              4 => 'LESS_THAN',
              5 => 'LESS_EQUAL',
              6 => 'LIKE',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('column_name', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'mail_pc',
              1 => 'mail_mobile',
              2 => 'mail_pc_flag',
              3 => 'mail_mobile_flag',
              4 => 'mail_html_flag',
              5 => 'sex',
              6 => 'prefecture',
              7 => 'birthday',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MailGroupLogic as Logic', array(
             'local' => 'logic_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}