<?php

/**
 * BaseProductSearchWrongWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $right_word_id
 * @property string $word
 * @property ProductSearchRightWord $RightWord
 * 
 * @method integer                getId()            Returns the current record's "id" value
 * @method integer                getRightWordId()   Returns the current record's "right_word_id" value
 * @method string                 getWord()          Returns the current record's "word" value
 * @method ProductSearchRightWord getRightWord()     Returns the current record's "RightWord" value
 * @method ProductSearchWrongWord setId()            Sets the current record's "id" value
 * @method ProductSearchWrongWord setRightWordId()   Sets the current record's "right_word_id" value
 * @method ProductSearchWrongWord setWord()          Sets the current record's "word" value
 * @method ProductSearchWrongWord setRightWord()     Sets the current record's "RightWord" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseProductSearchWrongWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_search_wrong_word');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('right_word_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('word', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));


        $this->index('word', array(
             'fields' => 
             array(
              0 => 'word',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ProductSearchRightWord as RightWord', array(
             'local' => 'right_word_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}