<?php

/**
 * BaseFaqContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title1
 * @property string $title2
 * @property string $title3
 * @property integer $priority
 * @property Doctrine_Collection $Details
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getTitle1()   Returns the current record's "title1" value
 * @method string              getTitle2()   Returns the current record's "title2" value
 * @method string              getTitle3()   Returns the current record's "title3" value
 * @method integer             getPriority() Returns the current record's "priority" value
 * @method Doctrine_Collection getDetails()  Returns the current record's "Details" collection
 * @method FaqContent          setId()       Sets the current record's "id" value
 * @method FaqContent          setTitle1()   Sets the current record's "title1" value
 * @method FaqContent          setTitle2()   Sets the current record's "title2" value
 * @method FaqContent          setTitle3()   Sets the current record's "title3" value
 * @method FaqContent          setPriority() Sets the current record's "priority" value
 * @method FaqContent          setDetails()  Sets the current record's "Details" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseFaqContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_content');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title2', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title3', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('orderBy', 'priority');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FaqDetail as Details', array(
             'refClass' => 'FaqContentDetail',
             'local' => 'faq_content_id',
             'foreign' => 'faq_detail_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}