<?php

/**
 * BaseShopFavorite
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $member_id
 * @property string $shop_id
 * @property Member $Member
 * @property Shop $Shop
 * 
 * @method integer      getMemberId()  Returns the current record's "member_id" value
 * @method string       getShopId()    Returns the current record's "shop_id" value
 * @method Member       getMember()    Returns the current record's "Member" value
 * @method Shop         getShop()      Returns the current record's "Shop" value
 * @method ShopFavorite setMemberId()  Sets the current record's "member_id" value
 * @method ShopFavorite setShopId()    Sets the current record's "shop_id" value
 * @method ShopFavorite setMember()    Sets the current record's "Member" value
 * @method ShopFavorite setShop()      Sets the current record's "Shop" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseShopFavorite extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('shop_favorite');
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('shop_id', 'string', 7, array(
             'type' => 'string',
             'primary' => true,
             'length' => 7,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Shop', array(
             'local' => 'shop_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}