<?php

/**
 * BaseCampaignEnquete
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property enum $q01
 * @property string $q02
 * @property enum $q03
 * @property string $q04
 * @property enum $q05
 * @property string $q06
 * 
 * @method integer         getId()        Returns the current record's "id" value
 * @method integer         getMemberId()  Returns the current record's "member_id" value
 * @method enum            getQ01()       Returns the current record's "q01" value
 * @method string          getQ02()       Returns the current record's "q02" value
 * @method enum            getQ03()       Returns the current record's "q03" value
 * @method string          getQ04()       Returns the current record's "q04" value
 * @method enum            getQ05()       Returns the current record's "q05" value
 * @method string          getQ06()       Returns the current record's "q06" value
 * @method CampaignEnquete setId()        Sets the current record's "id" value
 * @method CampaignEnquete setMemberId()  Sets the current record's "member_id" value
 * @method CampaignEnquete setQ01()       Sets the current record's "q01" value
 * @method CampaignEnquete setQ02()       Sets the current record's "q02" value
 * @method CampaignEnquete setQ03()       Sets the current record's "q03" value
 * @method CampaignEnquete setQ04()       Sets the current record's "q04" value
 * @method CampaignEnquete setQ05()       Sets the current record's "q05" value
 * @method CampaignEnquete setQ06()       Sets the current record's "q06" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseCampaignEnquete extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campaign_enquete');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('q01', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '知っていた',
              1 => '知っていて使用したこともある',
              2 => '知らなかった',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('q02', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('q03', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'クチコミをよくするほうだ',
              1 => 'クチコミはしない',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('q04', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('q05', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '普通肌',
              1 => '乾燥肌',
              2 => '脂性肌',
              3 => '混合肌',
              4 => '敏感肌',
              5 => 'アトピー',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('q06', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}