<?php

/**
 * BaseFaqCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title1
 * @property string $title2
 * @property string $title3
 * @property integer $priority
 * @property Doctrine_Collection $SubCategories
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getTitle1()        Returns the current record's "title1" value
 * @method string              getTitle2()        Returns the current record's "title2" value
 * @method string              getTitle3()        Returns the current record's "title3" value
 * @method integer             getPriority()      Returns the current record's "priority" value
 * @method Doctrine_Collection getSubCategories() Returns the current record's "SubCategories" collection
 * @method FaqCategory         setId()            Sets the current record's "id" value
 * @method FaqCategory         setTitle1()        Sets the current record's "title1" value
 * @method FaqCategory         setTitle2()        Sets the current record's "title2" value
 * @method FaqCategory         setTitle3()        Sets the current record's "title3" value
 * @method FaqCategory         setPriority()      Sets the current record's "priority" value
 * @method FaqCategory         setSubCategories() Sets the current record's "SubCategories" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseFaqCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title2', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title3', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('orderBy', 'priority');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('FaqSubCategory as SubCategories', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}