<?php

/**
 * BaseProductEffect
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $effect_id
 * @property Product $Product
 * @property Effect $Effect
 * 
 * @method integer       getProductId()  Returns the current record's "product_id" value
 * @method integer       getEffectId()   Returns the current record's "effect_id" value
 * @method Product       getProduct()    Returns the current record's "Product" value
 * @method Effect        getEffect()     Returns the current record's "Effect" value
 * @method ProductEffect setProductId()  Sets the current record's "product_id" value
 * @method ProductEffect setEffectId()   Sets the current record's "effect_id" value
 * @method ProductEffect setProduct()    Sets the current record's "Product" value
 * @method ProductEffect setEffect()     Sets the current record's "Effect" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseProductEffect extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_effect');
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('effect_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Effect', array(
             'local' => 'effect_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}