<?php

/**
 * BaseRedirectUrl
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $source
 * @property string $destination
 * @property string $destination_sp
 * @property string $destination_mb
 * 
 * @method integer     getId()             Returns the current record's "id" value
 * @method string      getSource()         Returns the current record's "source" value
 * @method string      getDestination()    Returns the current record's "destination" value
 * @method string      getDestinationSp()  Returns the current record's "destination_sp" value
 * @method string      getDestinationMb()  Returns the current record's "destination_mb" value
 * @method RedirectUrl setId()             Sets the current record's "id" value
 * @method RedirectUrl setSource()         Sets the current record's "source" value
 * @method RedirectUrl setDestination()    Sets the current record's "destination" value
 * @method RedirectUrl setDestinationSp()  Sets the current record's "destination_sp" value
 * @method RedirectUrl setDestinationMb()  Sets the current record's "destination_mb" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseRedirectUrl extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('redirect_url');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('source', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('destination', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('destination_sp', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('destination_mb', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));


        $this->index('source', array(
             'fields' => 
             array(
              0 => 'source',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}