<?php

/**
 * BaseCampaign
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $member_id
 * @property string $member_type
 * @property string $campaign_name
 * 
 * @method integer  getId()            Returns the current record's "id" value
 * @method integer  getMemberId()      Returns the current record's "member_id" value
 * @method string   getMemberType()    Returns the current record's "member_type" value
 * @method string   getCampaignName()  Returns the current record's "campaign_name" value
 * @method Campaign setId()            Sets the current record's "id" value
 * @method Campaign setMemberId()      Sets the current record's "member_id" value
 * @method Campaign setMemberType()    Sets the current record's "member_type" value
 * @method Campaign setCampaignName()  Sets the current record's "campaign_name" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseCampaign extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campaign');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('member_type', 'string', 20, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 20,
             ));
        $this->hasColumn('campaign_name', 'string', 30, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}