<?php

/**
 * BaseAttestation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property integer $member_id
 * @property enum $mail_type
 * @property Member $Member
 * 
 * @method string      getId()        Returns the current record's "id" value
 * @method integer     getMemberId()  Returns the current record's "member_id" value
 * @method enum        getMailType()  Returns the current record's "mail_type" value
 * @method Member      getMember()    Returns the current record's "Member" value
 * @method Attestation setId()        Sets the current record's "id" value
 * @method Attestation setMemberId()  Sets the current record's "member_id" value
 * @method Attestation setMailType()  Sets the current record's "mail_type" value
 * @method Attestation setMember()    Sets the current record's "Member" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseAttestation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('attestation');
        $this->hasColumn('id', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('member_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('mail_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'mb',
              1 => 'pc',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Member', array(
             'local' => 'member_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}