<?php

/**
 * BaseProductSearchRightWord
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $word
 * @property Doctrine_Collection $WrongWords
 * 
 * @method integer                getId()         Returns the current record's "id" value
 * @method string                 getWord()       Returns the current record's "word" value
 * @method Doctrine_Collection    getWrongWords() Returns the current record's "WrongWords" collection
 * @method ProductSearchRightWord setId()         Sets the current record's "id" value
 * @method ProductSearchRightWord setWord()       Sets the current record's "word" value
 * @method ProductSearchRightWord setWrongWords() Sets the current record's "WrongWords" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseProductSearchRightWord extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_search_right_word');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('word', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));


        $this->index('word', array(
             'fields' => 
             array(
              0 => 'word',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductSearchWrongWord as WrongWords', array(
             'local' => 'id',
             'foreign' => 'right_word_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}