<?php

/**
 * BaseFaqCategoryDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $faq_category_id
 * @property integer $faq_detail_id
 * @property FaqCategory $FaqCategory
 * @property FaqDetail $FaqDetail
 * 
 * @method integer           getFaqCategoryId()   Returns the current record's "faq_category_id" value
 * @method integer           getFaqDetailId()     Returns the current record's "faq_detail_id" value
 * @method FaqCategory       getFaqCategory()     Returns the current record's "FaqCategory" value
 * @method FaqDetail         getFaqDetail()       Returns the current record's "FaqDetail" value
 * @method FaqCategoryDetail setFaqCategoryId()   Sets the current record's "faq_category_id" value
 * @method FaqCategoryDetail setFaqDetailId()     Sets the current record's "faq_detail_id" value
 * @method FaqCategoryDetail setFaqCategory()     Sets the current record's "FaqCategory" value
 * @method FaqCategoryDetail setFaqDetail()       Sets the current record's "FaqDetail" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseFaqCategoryDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_category_detail');
        $this->hasColumn('faq_category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('faq_detail_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FaqCategory', array(
             'local' => 'faq_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FaqDetail', array(
             'local' => 'faq_detail_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}