<?php

/**
 * BaseSalonShopMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $shop_id
 * @property string $name
 * @property string $mb_name
 * @property integer $priority
 * @property SalonShop $Shop
 * 
 * @method integer       getId()       Returns the current record's "id" value
 * @method integer       getShopId()   Returns the current record's "shop_id" value
 * @method string        getName()     Returns the current record's "name" value
 * @method string        getMbName()   Returns the current record's "mb_name" value
 * @method integer       getPriority() Returns the current record's "priority" value
 * @method SalonShop     getShop()     Returns the current record's "Shop" value
 * @method SalonShopMenu setId()       Sets the current record's "id" value
 * @method SalonShopMenu setShopId()   Sets the current record's "shop_id" value
 * @method SalonShopMenu setName()     Sets the current record's "name" value
 * @method SalonShopMenu setMbName()   Sets the current record's "mb_name" value
 * @method SalonShopMenu setPriority() Sets the current record's "priority" value
 * @method SalonShopMenu setShop()     Sets the current record's "Shop" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseSalonShopMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('salon_shop_menu');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('shop_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('mb_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             ));

        $this->option('orderBy', 'priority');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('SalonShop as Shop', array(
             'local' => 'shop_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}