<?php

/**
 * BaseFaqSubCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property string $title1
 * @property string $title2
 * @property integer $priority
 * @property FaqCategory $Category
 * @property Doctrine_Collection $Details
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getCategoryId()  Returns the current record's "category_id" value
 * @method string              getTitle1()      Returns the current record's "title1" value
 * @method string              getTitle2()      Returns the current record's "title2" value
 * @method integer             getPriority()    Returns the current record's "priority" value
 * @method FaqCategory         getCategory()    Returns the current record's "Category" value
 * @method Doctrine_Collection getDetails()     Returns the current record's "Details" collection
 * @method FaqSubCategory      setId()          Sets the current record's "id" value
 * @method FaqSubCategory      setCategoryId()  Sets the current record's "category_id" value
 * @method FaqSubCategory      setTitle1()      Sets the current record's "title1" value
 * @method FaqSubCategory      setTitle2()      Sets the current record's "title2" value
 * @method FaqSubCategory      setPriority()    Sets the current record's "priority" value
 * @method FaqSubCategory      setCategory()    Sets the current record's "Category" value
 * @method FaqSubCategory      setDetails()     Sets the current record's "Details" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseFaqSubCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_sub_category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title1', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('title2', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('orderBy', 'priority');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FaqCategory as Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('FaqDetail as Details', array(
             'refClass' => 'FaqSubCategoryDetail',
             'local' => 'faq_sub_category_id',
             'foreign' => 'faq_detail_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}