<?php

/**
 * BaseMail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $subject
 * @property text $body
 * @property integer $author_id
 * @property integer $group_id
 * @property timestamp $delivered_at
 * @property enum $address_type
 * @property enum $status
 * @property MailAuthor $Author
 * @property MailGroup $Group
 * @property Doctrine_Collection $Logs
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getSubject()      Returns the current record's "subject" value
 * @method text                getBody()         Returns the current record's "body" value
 * @method integer             getAuthorId()     Returns the current record's "author_id" value
 * @method integer             getGroupId()      Returns the current record's "group_id" value
 * @method timestamp           getDeliveredAt()  Returns the current record's "delivered_at" value
 * @method enum                getAddressType()  Returns the current record's "address_type" value
 * @method enum                getStatus()       Returns the current record's "status" value
 * @method MailAuthor          getAuthor()       Returns the current record's "Author" value
 * @method MailGroup           getGroup()        Returns the current record's "Group" value
 * @method Doctrine_Collection getLogs()         Returns the current record's "Logs" collection
 * @method Mail                setId()           Sets the current record's "id" value
 * @method Mail                setSubject()      Sets the current record's "subject" value
 * @method Mail                setBody()         Sets the current record's "body" value
 * @method Mail                setAuthorId()     Sets the current record's "author_id" value
 * @method Mail                setGroupId()      Sets the current record's "group_id" value
 * @method Mail                setDeliveredAt()  Sets the current record's "delivered_at" value
 * @method Mail                setAddressType()  Sets the current record's "address_type" value
 * @method Mail                setStatus()       Sets the current record's "status" value
 * @method Mail                setAuthor()       Sets the current record's "Author" value
 * @method Mail                setGroup()        Sets the current record's "Group" value
 * @method Mail                setLogs()         Sets the current record's "Logs" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseMail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mail');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('author_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('delivered_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('address_type', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'PC',
              1 => '携帯',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('status', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '未送信',
              1 => '送信中',
              2 => '送信済み',
              3 => '送信エラー',
             ),
             'notnull' => true,
             ));

        $this->option('orderBy', 'id DESC');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('MailAuthor as Author', array(
             'local' => 'author_id',
             'foreign' => 'id'));

        $this->hasOne('MailGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasMany('MailLog as Logs', array(
             'local' => 'id',
             'foreign' => 'mail_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}