<?php

/**
 * BaseChildProduct
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property integer $parent_id
 * @property integer $sub_number
 * @property string $name
 * @property string $capacity
 * @property integer $price
 * @property string $slug
 * @property string $cn_shop_link_url
 * @property Product $Parent
 *
 * @method integer      getId()                 Returns the current record's "id" value
 * @method integer      getParentId()           Returns the current record's "parent_id" value
 * @method integer      getSubNumber()          Returns the current record's "sub_number" value
 * @method string       getName()               Returns the current record's "name" value
 * @method string       getCapacity()           Returns the current record's "capacity" value
 * @method integer      getPrice()              Returns the current record's "price" value
 * @method string       getSlug()               Returns the current record's "slug" value
 * @method string       getCnShopLinkUrl()      Returns the current record's "cn_shop_link_url" value
 * @method Product      getParent()             Returns the current record's "Parent" value
 * @method ChildProduct      setId()                 Sets the current record's "id" value
 * @method ChildProduct      setParentId()           Sets the current record's "parent_id" value
 * @method ChildProduct      setSubNumber()          Sets the current record's "sub_number" value
 * @method ChildProduct      setName()               Sets the current record's "name" value
 * @method ChildProduct      setCapacity()           Sets the current record's "capacity" value
 * @method ChildProduct      setPrice()              Sets the current record's "price" value
 * @method ChildProduct      setSlug()               Sets the current record's "slug" value
 * @method Product           setCnShopLinkUrl()      Sets the current record's "cn_shop_link_url" value
 * @method ChildProduct      setParent()             Sets the current record's "Parent" value
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseChildProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('child_product');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('parent_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sub_number', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('capacity', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('price', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cn_shop_link_url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
        ));


        $this->index('slug', array(
             'fields' =>
             array(
              0 => 'slug',
             ),
             'type' => 'unique',
             ));
        $this->index('name', array(
             'fields' =>
             array(
              0 => 'name',
             ),
             ));
        $this->index('capacity', array(
             'fields' =>
             array(
              0 => 'capacity',
             ),
             ));
        $this->index('price', array(
             'fields' =>
             array(
              0 => 'price',
             ),
             ));
        $this->option('orderBy', 'sub_number');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product as Parent', array(
             'local' => 'parent_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}
