<?php

/**
 * BaseFaqContentDetail
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $faq_content_id
 * @property integer $faq_detail_id
 * @property FaqContent $FaqContent
 * @property FaqDetail $FaqDetail
 * 
 * @method integer          getFaqContentId()   Returns the current record's "faq_content_id" value
 * @method integer          getFaqDetailId()    Returns the current record's "faq_detail_id" value
 * @method FaqContent       getFaqContent()     Returns the current record's "FaqContent" value
 * @method FaqDetail        getFaqDetail()      Returns the current record's "FaqDetail" value
 * @method FaqContentDetail setFaqContentId()   Sets the current record's "faq_content_id" value
 * @method FaqContentDetail setFaqDetailId()    Sets the current record's "faq_detail_id" value
 * @method FaqContentDetail setFaqContent()     Sets the current record's "FaqContent" value
 * @method FaqContentDetail setFaqDetail()      Sets the current record's "FaqDetail" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseFaqContentDetail extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_content_detail');
        $this->hasColumn('faq_content_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('faq_detail_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FaqContent', array(
             'local' => 'faq_content_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FaqDetail', array(
             'local' => 'faq_detail_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}