<?php

/**
 * BaseSubCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property string $name
 * @property integer $priority
 * @property string $slug
 * @property Category $Category
 * @property Doctrine_Collection $Products
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getCategoryId()  Returns the current record's "category_id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method integer             getPriority()    Returns the current record's "priority" value
 * @method string              getSlug()        Returns the current record's "slug" value
 * @method Category            getCategory()    Returns the current record's "Category" value
 * @method Doctrine_Collection getProducts()    Returns the current record's "Products" collection
 * @method SubCategory         setId()          Sets the current record's "id" value
 * @method SubCategory         setCategoryId()  Sets the current record's "category_id" value
 * @method SubCategory         setName()        Sets the current record's "name" value
 * @method SubCategory         setPriority()    Sets the current record's "priority" value
 * @method SubCategory         setSlug()        Sets the current record's "slug" value
 * @method SubCategory         setCategory()    Sets the current record's "Category" value
 * @method SubCategory         setProducts()    Sets the current record's "Products" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseSubCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_category');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('priority', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('slug', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));


        $this->index('slug', array(
             'fields' => 
             array(
              0 => 'slug',
             ),
             'type' => 'unique',
             ));
        $this->index('name', array(
             'fields' => 
             array(
              0 => 'name',
             ),
             ));
        $this->option('orderBy', 'priority');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasMany('Product as Products', array(
             'local' => 'id',
             'foreign' => 'sub_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}