<?php

/**
 * BaseMailGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Mails
 * @property Doctrine_Collection $Logics
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method string              getName()   Returns the current record's "name" value
 * @method Doctrine_Collection getMails()  Returns the current record's "Mails" collection
 * @method Doctrine_Collection getLogics() Returns the current record's "Logics" collection
 * @method MailGroup           setId()     Sets the current record's "id" value
 * @method MailGroup           setName()   Sets the current record's "name" value
 * @method MailGroup           setMails()  Sets the current record's "Mails" collection
 * @method MailGroup           setLogics() Sets the current record's "Logics" collection
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseMailGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mail_group');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Mail as Mails', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $this->hasMany('MailGroupLogic as Logics', array(
             'local' => 'id',
             'foreign' => 'group_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}