<?php

/**
 * BaseFaqDetailRelated
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $faq_detail_id1
 * @property integer $faq_detail_id2
 * @property FaqDetail $FaqDetail1
 * @property FaqDetail $FaqDetail2
 * 
 * @method integer          getFaqDetailId1()   Returns the current record's "faq_detail_id1" value
 * @method integer          getFaqDetailId2()   Returns the current record's "faq_detail_id2" value
 * @method FaqDetail        getFaqDetail1()     Returns the current record's "FaqDetail1" value
 * @method FaqDetail        getFaqDetail2()     Returns the current record's "FaqDetail2" value
 * @method FaqDetailRelated setFaqDetailId1()   Sets the current record's "faq_detail_id1" value
 * @method FaqDetailRelated setFaqDetailId2()   Sets the current record's "faq_detail_id2" value
 * @method FaqDetailRelated setFaqDetail1()     Sets the current record's "FaqDetail1" value
 * @method FaqDetailRelated setFaqDetail2()     Sets the current record's "FaqDetail2" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseFaqDetailRelated extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('faq_detail_related');
        $this->hasColumn('faq_detail_id1', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('faq_detail_id2', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('FaqDetail as FaqDetail1', array(
             'local' => 'faq_detail_id1',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('FaqDetail as FaqDetail2', array(
             'local' => 'faq_detail_id2',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}