<?php

/**
 * BaseProductPopular
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property integer $product_id
 * @property integer $ranking
 * @property Product $Product
 * @property Category $Category
 * 
 * @method integer        getId()          Returns the current record's "id" value
 * @method integer        getCategoryId()  Returns the current record's "category_id" value
 * @method integer        getProductId()   Returns the current record's "product_id" value
 * @method integer        getRanking()     Returns the current record's "ranking" value
 * @method Product        getProduct()     Returns the current record's "Product" value
 * @method Category       getCategory()    Returns the current record's "Category" value
 * @method ProductPopular setId()          Sets the current record's "id" value
 * @method ProductPopular setCategoryId()  Sets the current record's "category_id" value
 * @method ProductPopular setProductId()   Sets the current record's "product_id" value
 * @method ProductPopular setRanking()     Sets the current record's "ranking" value
 * @method ProductPopular setProduct()     Sets the current record's "Product" value
 * @method ProductPopular setCategory()    Sets the current record's "Category" value
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
abstract class BaseProductPopular extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_popular');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('product_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ranking', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}