generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Line
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          line
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        name: { label: 名前 }
        name_en: { label: 名前(英語) }
        skincare_system_flag: { label: スキンケアシステム }
        major_flag: { label: メジャー }
        priority: { label: 優先度 }
        slug: { label: スラッグ }
        search_index: { label: 検索インデックス }
      list:
        title: ライン 一覧
        display: [ name, slug, priority, major_flag, skincare_system_flag ]
        object_actions:
          _edit:   { label: 編集 }
          _delete: { label: 削除, confirm: "本当に削除してもよろしいですか?" }
<?php if ($_SERVER['HTTP_HOST'] != 'www.cosmedecorte.com'): ?>
          liveup:  { label: 本番反映, action: liveup, params: { onclick : "if (confirm('本当に本番反映してもよろしいですか?')) { return true; } else { return false; }" } }
<?php endif ?>
        batch_actions:
          _delete: { label: 削除 }
<?php if ($_SERVER['HTTP_HOST'] != 'www.cosmedecorte.com'): ?>
          liveup:  { label: 本番反映, action: liveup }
<?php endif ?>
      filter:
        class: false
      form:
        display: [ name, name_en, slug, priority, major_flag, skincare_system_flag, search_index ]
      edit:
        title: ライン 編集
      new:
        title: ライン 新規作成
