<?php

/**
 * Attestation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Attestation.class.php 12 2011-05-12 03:42:19Z oda $
 */
class Attestation extends BaseAttestation
{

}