<?php

/**
 * CampaignTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampaignTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampaignTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Campaign');
    }
}