<?php

/**
 * Category
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Category.class.php 1194 2012-10-26 07:08:28Z oda $
 */
class Category extends BaseCategory
{
    /**
     * 半角文字を使用したカテゴリ名を返却する。
     *
     * @return string 半角文字を使用したカテゴリ名
     */
    public function getHName()
    {
        return Util::convertStringIntoHalfWidth($this->getName());
    }

    /**
     * オブジェクトの現在の内容を本番環境に反映させる。
     */
    public function liveup()
    {
        Doctrine_Manager::getInstance()->setCurrentConnection('livedb');

        $live_category =
           CategoryTable::getInstance()->findOneBySlug($this->getSlug());

        if ($live_category) {
            $values = $this->toArray();
            unset($values['id']);
            unset($values['created_at']);
            unset($values['updated_at']);
            $live_category->fromArray($values);
            $live_category->setUpdatedAt(null);
        } else {
            $live_category = $this->copy();
            $live_category->setCreatedAt(null);
            $live_category->setUpdatedAt(null);
        }
        $live_category->
            save(Doctrine_Manager::getInstance()->getConnection('livedb'));

        Doctrine_Manager::getInstance()->setCurrentConnection('doctrine');
    }
}
