<?php

/**
 * CategoryTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }

    public function findBySlugParam(array $params)
    {
        if (isset($params['slug'])) {
            $product_slug = $params['slug'];
        }

        return $this->findOneBySlug($params['slug']);
    }
}
