<?php

/**
 * ChildProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChildProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChildProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChildProduct');
    }
}