<?php

/**
 * EffectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EffectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EffectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Effect');
    }
}