<?php

/**
 * ExistingMobileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExistingMobileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExistingMobileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExistingMobile');
    }

}
