<?php

/**
 * ExistingWithdrawalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ExistingWithdrawalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ExistingWithdrawalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ExistingWithdrawal');
    }
}