<?php

/**
 * FaqContentTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaqContent');
    }

    public function findTop()
    {
        return $this->createQuery('c')->fetchOne();
    }
}
