<?php

/**
 * FaqCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
class FaqCategory extends BaseFaqCategory
{
    public function getHTitle1()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('title1'));
    }

    public function getHTitle2()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('title2'));
    }

    public function getHTitle3()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('title3'));
    }

    public function getNonemptySubCategories()
    {
        return FaqSubCategoryTable::getInstance()->createQuery('s')->
            innerJoin('s.Details d')->
            where('s.category_id = ?', $this->getId())->
            orderBy('s.priority, d.priority')->execute();
    }
}
