<?php

/**
 * FaqContentDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqContentDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqContentDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaqContentDetail');
    }
}