<?php

/**
 * FaqDetailTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaqDetail');
    }

    public function getPopularsQuery()
    {
        return $this->createQuery('f')->
            where('popular_flag = ?', true)->orderBy('priority');
    }

    public function getPopulars()
    {
        return $this->getPopularsQuery()->execute();
    }
}
