<?php

/**
 * FaqDetailRelatedTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqDetailRelatedTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqDetailRelatedTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaqDetailRelated');
    }
}