<?php

/**
 * FaqDetail
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
class FaqDetail extends BaseFaqDetail
{
    public function getHQuestion()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('question'));
    }

    public function getHAnswer()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('answer'));
    }
}
