<?php

/**
 * FaqSubCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
class FaqSubCategory extends BaseFaqSubCategory
{
    public function getDetailsQuery()
    {
        return FaqDetailTable::getInstance()->createQuery('d')->
            innerJoin('d.FaqSubCategoryDetail sd')->
            innerJoin('sd.FaqSubCategory s')->
            where('s.id = ' . $this->getId())->orderBy('d.priority');
    }

    public function getHTitle1()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('title1'));
    }

    public function getHTitle2()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('title2'));
    }

    public function __toString()
    {
        return $this->getTitle1();
    }
}
