<?php

/**
 * FaqSubCategoryDetailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FaqSubCategoryDetailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FaqSubCategoryDetailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FaqSubCategoryDetail');
    }
}