<?php

/**
 * Line
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
class Line extends BaseLine
{
    public static function findLineName()
    {
        $line_name = array();
        $q = Doctrine_Query::create()
            ->select('b.name')
            ->from('Line l');

        $names = $q->fetchArray();
        foreach ($names as $key => $group) {
            $line_name[$key]=$group['name'];
        }
        return $line_name;
    }

    /**
     * 半角文字を使用したライン名を返却する。
     *
     * @return string 半角文字を使用したライン名
     */
    public function getHName()
    {
        return Util::convertStringIntoHalfWidth($this->getName());
    }

    /**
     * ラインロゴ画像ファイルの絶対パスを取得する。
     */
    public function getAbsoluteImagePath()
    {
        return sfConfig::get('sf_web_dir') .
            '/images/' . $this->getRelativeImagePath();
    }

    /**
     * ラインロゴ画像ファイルの相対パス(images からの相対パス)を取得する。
     */
    public function getRelativeImagePath()
    {
        return 'line/' . $this->getSlug() . '.png';
    }

    /**
     * オブジェクトの現在の内容を本番環境に反映させる。
     */
    public function liveup()
    {
        Doctrine_Manager::getInstance()->setCurrentConnection('livedb');

        $live_line =
           LineTable::getInstance()->findOneBySlug($this->getSlug());

        if ($live_line) {
            $values = $this->toArray();
            unset($values['id']);
            unset($values['created_at']);
            unset($values['updated_at']);
            $live_line->fromArray($values);
            $live_line->setUpdatedAt(null);
        } else {
            $live_line = $this->copy();
            $live_line->setCreatedAt(null);
            $live_line->setUpdatedAt(null);
        }
        $live_line->
            save(Doctrine_Manager::getInstance()->getConnection('livedb'));

        Doctrine_Manager::getInstance()->setCurrentConnection('doctrine');
    }
}
