<?php

/**
 * LineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Line');
    }
}