<?php

/**
 * MailGroupLogic
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: MailGroupLogic.class.php 92 2011-05-27 02:46:37Z oda $
 */
class MailGroupLogic extends BaseMailGroupLogic
{
    public function getOperatorExpression()
    {
        $expressions =
            MailGroupLogicTable::getInstance()->getOperatorExpressions();
        return $expressions[$this->getOperator()];
    }
}
