<?php

/**
 * MailLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: MailLog.class.php 32 2011-05-18 09:16:59Z oda $
 */
class MailLog extends BaseMailLog
{

}