<?php

/**
 * MailAuthorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailAuthorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailAuthorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailAuthor');
    }
}