<?php

/**
 * MailLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailLog');
    }
}