<?php

/**
 * MailGroupLogicTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailGroupLogicTable extends Doctrine_Table
{
    protected static $operator_expressions =
        array('AND' => '以下の全ての条件を満たす',
              'OR' => '以下のいずれかの条件を満たす');

    /**
     * Returns an instance of this class.
     *
     * @return object MailGroupLogicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailGroupLogic');
    }

    public function getOperatorExpressions()
    {
        return self::$operator_expressions;
    }
}
