<?php

/**
 * MailGroupTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailGroupTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailGroupTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailGroup');
    }

    public function withLogics(Doctrine_Query $query)
    {
        $query->leftJoin('a.Logics l')->leftJoin('l.Terms t');
        return $query->execute();
    }
}
