<?php

/**
 * MailTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mail');
    }

    public function deliverUnsent(sfMailer $mailer)
    {
        $conn = Doctrine_Manager::connection();

        $conn->beginTransaction();
        $mails = null;

        try {
            $now = date('Y-m-d H:i:s');
            $mails = $this->createQuery()->
                forUpdate(true)->
                where('delivered_at <= ?', $now)->
                addWhere('status = ?', '未送信')->
                execute();

            foreach ($mails as $mail) {
                $mail->setStatus('送信中');
                $mail->save();
            }

            $conn->commit();
        } catch (Exception $e) {
            $conn->rollback();
            return;
        }

        foreach ($mails as $mail) {
            echo "delivering mail id=" . $mail->getId() . "...\n";
            try {
                $count = $mail->send($mailer);
                $mail->setStatus('送信済み');
                $mail->save();
                echo "done for " . $count . " members.\n";
            } catch (Exception $e) {
                $mail->setStatus('送信エラー');
                $mail->save();
                echo "error! stopped on the way.\n";
            }
        }
    }
}
