<?php

/**
 * MailGroup
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: MailGroup.class.php 111 2011-06-08 05:00:22Z oda $
 */
class MailGroup extends BaseMailGroup
{
    public function getMembersQuery()
    {
        $query = MemberTable::getInstance()->createQuery();

        foreach ($this->getLogics() as $logic) {
            $where_stmt = '';
            $where_values = array();
            foreach ($logic->getTerms() as $term) {
                if ($where_stmt != '') {
                    if ($logic->getOperator() == 'OR') {
                        $where_stmt .= ' OR ';
                    } else {
                        $where_stmt .= ' AND ';
                    }
                }

                $where_stmt .= $term->getColumnName();
                switch ($term->getOperator()) {
                case 'EQUAL':
                    $where_stmt .= ' = ?';
                    $where_values[] = $term->getValue();
                    break;
                case 'NOT_EQUAL':
                    $where_stmt .= ' != ?';
                    $where_values[] = $term->getValue();
                    break;
                case 'GREATER_THAN':
                    $where_stmt .= ' > ?';
                    $where_values[] = $term->getValue();
                    break;
                case 'GREATER_EQUAL':
                    $where_stmt .= ' >= ?';
                    $where_values[] = $term->getValue();
                    break;
                case 'LESS_THAN':
                    $where_stmt .= ' < ?';
                    $where_values[] = $term->getValue();
                    break;
                case 'LESS_EQUAL':
                    $where_stmt .= ' <= ?';
                    $where_values[] = $term->getValue();
                    break;
                case 'LIKE':
                    $where_stmt .= ' LIKE ?';
                    $where_values[] = '%' . $term->getValue() . '%';
                    break;
               }
            }

            if ($where_stmt) {
                $query->andWhere($where_stmt, $where_values);
            }
        }

        $query->addWhere('temp_flag = ?', false);
        $query->addWhere('mail_block_flag = ?', false);

        return $query;
    }

    public function getMembers()
    {
        return $this->getMembersQuery()->execute();
    }

    public function preSave($event)
    {
        Doctrine_Query::create()->
            delete()->
            from('MailGroupLogic')->
            where('group_id = ?', $this->getId())->
            execute();
    }
}
