<?php

/**
 * MailGroupLogicTerm
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: MailGroupLogicTerm.class.php 92 2011-05-27 02:46:37Z oda $
 */
class MailGroupLogicTerm extends BaseMailGroupLogicTerm
{
    public function getOperatorExpression()
    {
        $expressions =
            MailGroupLogicTermTable::getInstance()->getOperatorExpressions();
        return $expressions[$this->getOperator()];
    }

    public function getColumnNameExpression()
    {
        $expressions =
            MailGroupLogicTermTable::getInstance()->getColumnNameExpressions();
        return $expressions[$this->getColumnName()];
    }
}
