<?php

/**
 * MailGroupLogicTermTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MailGroupLogicTermTable extends Doctrine_Table
{
    protected static $operator_expressions =
        array('EQUAL' => 'と等しい',
              'NOT EQUAL' => 'と異なる',
              'GREATER_THAN' => 'より大きい',
              'GREATER_EQUAL' => '以上',
              'LESS_THAN' => 'より小さい',
              'LESS_EQUAL' => '以下',
              'LIKE' => 'を含む');

    protected static $column_name_expressions =
        array('mail_pc' => 'PCメールアドレス',
              'mail_mobile' => '携帯メールアドレス',
              'mail_pc_flag' => 'PCメルマガ希望フラグ',
              'mail_mobile_flag' => '携帯メルマガ希望フラグ',
              'mail_html_flag' => 'HTMLメール希望フラグ',
              'sex' => '性別',
              'prefecture' => '都道府県',
              'birthday' => '誕生日');

    /**
     * Returns an instance of this class.
     *
     * @return object MailGroupLogicTermTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MailGroupLogicTerm');
    }

    public function getOperatorExpressions()
    {
        return self::$operator_expressions;
    }

    public function getColumnNameExpressions()
    {
        return self::$column_name_expressions;
    }
}
