<?php

/**
 * ProductSearchIndexTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSearchIndexTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSearchIndexTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSearchIndex');
    }
}