<?php

/**
 * ProductFavoriteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductFavoriteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductFavoriteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductFavorite');
    }
}