<?php

/**
 * ProductSearchWrongWordTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSearchWrongWordTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSearchWrongWordTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSearchWrongWord');
    }
}