<?php

/**
 * ProductSearchLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSearchLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSearchLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSearchLog');
    }
}