<?php

/**
 * ProductSearchWrongWord
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
class ProductSearchWrongWord extends BaseProductSearchWrongWord
{
    public function __toString()
    {
        return $this->getWord();
    }
}
