<?php

/**
 * ProductEffectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductEffectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductEffectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductEffect');
    }
}