<?php

/**
 * ProductTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }

    public function getQueryBySlugs(
        $product_slug = null, $line_slug = null,
        $category_slug = null, $subcategory_slug = null)
    {
        $query = $this->createQuery('p')->
            leftJoin('p.Line l')->
            leftJoin('p.Category c')->
            leftJoin('p.SubCategory s');

        if (isset($product_slug)) {
            $query->addWhere('p.slug = ?', $product_slug);
        }
        if (isset($line_slug)) {
            $query->addWhere('l.slug = ?', $line_slug);
            $query->addOrderBy('p.line_priority');
        }
        if (isset($category_slug)) {
            $query->addWhere('c.slug = ?', $category_slug);
        }
        if (isset($subcategory_slug)) {
            $query->addWhere('s.slug = ?', $subcategory_slug);
        }
        $query->addWhere('p.search_only_flag = ?', false);

        return $query;
    }

    public function findBySlugParams(array $params)
    {
        $product_slug = null;
        $line_slug = null;
        $category_slug = null;
        $subcategory_slug = null;

        if (isset($params['slug'])) {
            $product_slug = $params['slug'];
        }
        if (isset($params['line_slug'])) {
            $line_slug = $params['line_slug'];
        }
        if (isset($params['category_slug'])) {
            $category_slug = $params['category_slug'];
        }
        if (isset($params['subcategory_slug'])) {
            $subcategory_slug = $params['subcategory_slug'];
        }

        return $this->getQueryBySlugs(
            $product_slug, $line_slug, $category_slug, $subcategory_slug)->
            execute();
    }
}
