<?php

/**
 * ProductIngredient
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
class ProductIngredient extends BaseProductIngredient
{
    /**
     * 半角文字を使用したシンボルを返却する。
     *
     * @return string 半角文字を使用したシンボル
     */
    public function getHSymbol()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('symbol'));
    }

    /**
     * 半角文字を使用した内容(コンテント)を返却する。
     *
     * @return string 半角文字を使用した内容(コンテント)
     */
    public function getHContent()
    {
        return Util::convertStringIntoHalfWidth(parent::_get('content'));
    }
}
