<?php

/**
 * ProductAccessLogTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductAccessLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductAccessLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductAccessLog');
    }

    public function getPopularProducts($limit = 10, Category $category = null)
    {
        $now = floor(time() / 60) * 60;
        $from = $now - ((60 * 60 * 24) *
                       sfConfig::get('app_product_ranking_period'));

        $query = $this->createQuery('a')->
            select('a.product_id, count(*)')->
            where('created_at >= ?', date('Y-m-d H:i:s', $from))->
            groupBy('product_id')->
            orderBy('count desc')->
            limit($limit);
        if ($category) {
            $query->leftJoin('a.Product p')->
                addWhere('p.category_id = ?', $category->getId());
        }

        $results = $query->execute();

        $products = array();
        foreach ($results as $result) {
            $products[] = $result->getProduct();
        }

        return $products;
    }
}
