<?php

/**
 * ProductIngredientTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductIngredientTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductIngredientTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductIngredient');
    }
}