<?php

/**
 * ProductFriendTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductFriendTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductFriendTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductFriend');
    }
}