<?php

/**
 * ProductSearchKeywordLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSearchKeywordLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSearchKeywordLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSearchKeywordLog');
    }
}