<?php

/**
 * RedirectUrl
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    cosmedecorte
 * @subpackage model
 * @author     BROADTECH INC.
 * @version    SVN: $Id: Builder.php 12 2011-05-12 03:42:19Z oda $
 */
class RedirectUrl extends BaseRedirectUrl
{
    public function getDestinations()
    {
        $destinations = $this->getDestination();

        $dest_sp = $this->getDestinationSp();
        if ($dest_sp) {
            $destinations .= "\n" . $dest_sp;
        }

        $dest_mb = $this->getDestinationMb();
        if ($dest_mb) {
            $destinations .= "\n" . $dest_mb;
        }

        return $destinations;
    }
}
