<?php

/**
 * RedirectUrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RedirectUrlTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RedirectUrlTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RedirectUrl');
    }
}