<?php

/**
 * ReserveDecisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReserveDecisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReserveDecisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ReserveDecision');
    }
}