<?php

/**
 * SalonShopMenuTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalonShopMenuTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalonShopMenuTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalonShopMenu');
    }
}