<?php

/**
 * SalonShopTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SalonShopTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SalonShopTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SalonShop');
    }
}