<?php

/**
 * ShopFavoriteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ShopFavoriteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ShopFavoriteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ShopFavorite');
    }
}