<?php

/**
 * SubCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubCategory');
    }
}