generator:
  class: sfDoctrineGenerator
  param:
    model_class:           FaqDetail
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          faq_detail
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: { label: ID }
        question: { label: 質問(Q) }
        answer: { label: 回答(A) }
        priority: { label: 表示優先度 }
        popular_flag: { label: よく頂く質問 }
        search_index: { label: 検索インデックス }
        related_details_list: { label: 関連FAQ }
        sub_categories_list: { label: サブカテゴリ }
        contents_list: { label: 質問内容 }
      list:
        title: FAQ 一覧
        display: [ id, question, priority, popular_flag ]
        object_actions:
          _edit:   { label: 編集 }
          _delete: { label: 削除, confirm: "本当に削除してもよろしいですか?" }
      filter:
        class: AdminFaqDetailFormFilter
        display: [ question, answer, popular_flag, sub_categories_list, contents_list ]
      form:    ~
      edit:
        title: FAQ 編集
      new:
        title: FAQ 新規作成
